
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ASTERISK COMMA DOT EQ GT LPAREN LT NUMBER RPAREN STRING WORDstatement : statement token\n                 | tokentoken : WORD\n              | NUMBER\n              | GT\n              | LT\n              | EQ\n              | STRING\n              | LPAREN\n              | RPAREN\n              | COMMA\n              | ASTERISK\n              | DOT'
    
_lr_action_items = {'WORD':([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,],[3,3,-2,-3,-4,-5,-6,-7,-8,-9,-10,-11,-12,-13,-1,]),'NUMBER':([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,],[4,4,-2,-3,-4,-5,-6,-7,-8,-9,-10,-11,-12,-13,-1,]),'GT':([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,],[5,5,-2,-3,-4,-5,-6,-7,-8,-9,-10,-11,-12,-13,-1,]),'LT':([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,],[6,6,-2,-3,-4,-5,-6,-7,-8,-9,-10,-11,-12,-13,-1,]),'EQ':([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,],[7,7,-2,-3,-4,-5,-6,-7,-8,-9,-10,-11,-12,-13,-1,]),'STRING':([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,],[8,8,-2,-3,-4,-5,-6,-7,-8,-9,-10,-11,-12,-13,-1,]),'LPAREN':([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,],[9,9,-2,-3,-4,-5,-6,-7,-8,-9,-10,-11,-12,-13,-1,]),'RPAREN':([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,],[10,10,-2,-3,-4,-5,-6,-7,-8,-9,-10,-11,-12,-13,-1,]),'COMMA':([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,],[11,11,-2,-3,-4,-5,-6,-7,-8,-9,-10,-11,-12,-13,-1,]),'ASTERISK':([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,],[12,12,-2,-3,-4,-5,-6,-7,-8,-9,-10,-11,-12,-13,-1,]),'DOT':([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,],[13,13,-2,-3,-4,-5,-6,-7,-8,-9,-10,-11,-12,-13,-1,]),'$end':([1,2,3,4,5,6,7,8,9,10,11,12,13,14,],[0,-2,-3,-4,-5,-6,-7,-8,-9,-10,-11,-12,-13,-1,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'statement':([0,],[1,]),'token':([0,1,],[2,14,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statement","S'",1,None,None,None),
  ('statement -> statement token','statement',2,'p_statement_select','dsl_parser.py',7),
  ('statement -> token','statement',1,'p_statement_select','dsl_parser.py',8),
  ('token -> WORD','token',1,'p_token','dsl_parser.py',15),
  ('token -> NUMBER','token',1,'p_token','dsl_parser.py',16),
  ('token -> GT','token',1,'p_token','dsl_parser.py',17),
  ('token -> LT','token',1,'p_token','dsl_parser.py',18),
  ('token -> EQ','token',1,'p_token','dsl_parser.py',19),
  ('token -> STRING','token',1,'p_token','dsl_parser.py',20),
  ('token -> LPAREN','token',1,'p_token','dsl_parser.py',21),
  ('token -> RPAREN','token',1,'p_token','dsl_parser.py',22),
  ('token -> COMMA','token',1,'p_token','dsl_parser.py',23),
  ('token -> ASTERISK','token',1,'p_token','dsl_parser.py',24),
  ('token -> DOT','token',1,'p_token','dsl_parser.py',25),
]
